// AUTO-GENERATED oleh scripts/audit-bagian.mjs — JANGAN diedit manual.
// Perbarui dengan: npm run audit:bagian (juga jalan otomatis sebelum dev/build).

/** Bagian yang belum punya elemen/komponen nyata di project (hanya pratinjau). */
export const BELUM_DIPAKAI: ReadonlySet<string> = new Set([
  'tab_ribbon',
  'aspect_ratio',
  'scroll_area',
  'collapsible',
  'tabs',
  'breadcrumb',
  'pagination',
  'navigation_menu',
  'kbd',
  'empty',
  'tabel',
  'input_group',
  'textarea',
  'radio',
  'slider',
  'input_otp',
  'calendar',
  'button_group',
  'hover_card',
  'tooltip',
  'command',
  'sheet',
  'drawer',
  'alert',
  'progress',
  'spinner',
  'avatar',
  'carousel',
  'chart',
]);
