/** Terjemahan Bahasa Indonesia untuk Filerobot Image Editor (111 kunci).
 *  Dipakai dengan `useBackendTranslations={false}` agar editor bekerja offline
 *  tanpa menelepon layanan terjemahan Scaleflex. */

export const TERJEMAHAN_EDITOR_ID: Record<string, string> = {
  name: 'Nama',
  save: 'Simpan',
  saveAs: 'Simpan sebagai',
  back: 'Kembali',
  loading: 'Memuat...',
  resetOperations: 'Atur ulang/hapus semua operasi',
  changesLoseWarningHint: 'Jika Anda menekan tombol \u201Catul ulang\u201D, perubahan akan hilang. Lanjutkan?',
  discardChangesWarningHint: 'Jika menutup editor, perubahan terakhir tidak tersimpan.',
  cancel: 'Batal',
  apply: 'Terapkan',
  warning: 'Peringatan',
  confirm: 'Konfirmasi',
  discardChanges: 'Buang perubahan',
  undoTitle: 'Urungkan operasi terakhir',
  redoTitle: 'Ulangi operasi terakhir',
  showImageTitle: 'Tampilkan gambar asli',
  zoomInTitle: 'Perbesar',
  zoomOutTitle: 'Perkecil',
  toggleZoomMenuTitle: 'Buka/tutup menu zoom',
  adjustTab: 'Sesuaikan',
  finetuneTab: 'Haluskan',
  filtersTab: 'Filter',
  watermarkTab: 'Tanda air',
  annotateTabLabel: 'Anotasi',
  resize: 'Ubah ukuran',
  resizeTab: 'Ubah ukuran',
  imageName: 'Nama gambar',
  invalidImageError: 'Gambar tidak valid.',
  uploadImageError: 'Gagal mengunggah gambar.',
  areNotImages: 'bukan gambar',
  isNotImage: 'bukan gambar',
  toBeUploaded: 'yang akan diunggah',
  cropTool: 'Potong',
  original: 'Asli',
  custom: 'Kustom',
  square: 'Persegi',
  landscape: 'Lanskap',
  portrait: 'Potret',
  ellipse: 'Elips',
  classicTv: 'TV Klasik',
  cinemascope: 'Sinema',
  arrowTool: 'Panah',
  blurTool: 'Blur',
  brightnessTool: 'Kecerahan',
  contrastTool: 'Kontras',
  ellipseTool: 'Elips',
  unFlipX: 'Batalkan Balik X',
  flipX: 'Balik X',
  unFlipY: 'Batalkan Balik Y',
  flipY: 'Balik Y',
  hsvTool: 'HSV',
  hue: 'Rona',
  brightness: 'Kecerahan',
  saturation: 'Saturasi',
  value: 'Nilai',
  imageTool: 'Gambar',
  importing: 'Mengimpor...',
  addImage: '+ Tambah gambar',
  uploadImage: 'Unggah gambar',
  fromGallery: 'Dari galeri',
  lineTool: 'Garis',
  penTool: 'Pena',
  polygonTool: 'Poligon',
  sides: 'Sisi',
  rectangleTool: 'Persegi panjang',
  cornerRadius: 'Radius sudut',
  resizeWidthTitle: 'Lebar dalam piksel',
  resizeHeightTitle: 'Tinggi dalam piksel',
  toggleRatioLockTitle: 'Kunci rasio',
  resetSize: 'Kembalikan ke ukuran asli',
  rotateTool: 'Putar',
  textTool: 'Teks',
  textSpacings: 'Spasi teks',
  textAlignment: 'Perataan teks',
  fontFamily: 'Jenis huruf',
  size: 'Ukuran',
  letterSpacing: 'Spasi huruf',
  lineHeight: 'Tinggi baris',
  warmthTool: 'Kehangatan',
  addWatermark: '+ Tambah tanda air',
  addTextWatermark: '+ Tambah tanda air teks',
  addWatermarkTitle: 'Pilih jenis tanda air',
  uploadWatermark: 'Unggah tanda air',
  addWatermarkAsText: 'Tambah sebagai teks',
  padding: 'Padding',
  paddings: 'Padding',
  shadow: 'Bayangan',
  horizontal: 'Horisontal',
  vertical: 'Vertikal',
  blur: 'Blur',
  opacity: 'Opasitas',
  transparency: 'Transparansi',
  position: 'Posisi',
  stroke: 'Garis tepi',
  saveAsModalTitle: 'Simpan sebagai',
  extension: 'Ekstensi',
  format: 'Format',
  nameIsRequired: 'Nama wajib diisi.',
  quality: 'Kualitas',
  imageDimensionsHoverTitle: 'Ukuran gambar tersimpan (lebar x tinggi)',
  cropSizeLowerThanResizedWarning: 'Catatan, area potong lebih kecil dari resize yang diterapkan sehingga kualitas bisa menurun',
  actualSize: 'Ukuran sebenarnya (100%)',
  fitSize: 'Ukuran pas',
  addImageTitle: 'Pilih gambar untuk ditambah...',
  mutualizedFailedToLoadImg: 'Gagal memuat gambar.',
  tabsMenu: 'Menu',
  download: 'Unduh',
  width: 'Lebar',
  height: 'Tinggi',
  plus: '+',
  cropItemNoEffect: 'Tidak ada pratinjau untuk item potong ini',
};
